Repository roothide/Bootstrap, pull requests merged in 2024-01, with the labels that each got.

#55 Revert "Swift UI"
  .github/workflows/Bulid.yml
Labels: enhancement

#160 Localization(zh-CN)
  Bootstrap/zh-CN.lproj/Localizable.strings
Labels: enhancement, translation

#161 Add German Localization
  Bootstrap/de.lproj/Localizable.strings
Labels: enhancement, translation

#157 Add Vietnamese translation (complete translation)
  Bootstrap.xcodeproj/project.pbxproj
  Bootstrap/vi.lproj/Localizable.strings
Labels: enhancement, translation

#149 Fix Indonesian Localizable.strings
  Bootstrap/id.lproj/Localizable.strings
Labels: enhancement, translation

#137 russian translate
  Bootstrap/ru.lproj/Localizable.strings
Labels: enhancement, translation

#140 Update Localizable.strings ;fr
  Bootstrap/fr.lproj/Localizable.strings
Labels: enhancement, translation

#142 Localization Spanish!
  Bootstrap/es.lproj/Localizable.strings
Labels: enhancement, translation

#152 Localization Thai [th-TH]
  Bootstrap/th.lproj/Localizable.strings
Labels: enhancement, translation

#156 Update Localizable.strings (Kr)
  Bootstrap/en.lproj/Localizable.strings
Labels: enhancement, translation

#147 Localization (pt-BR)
  Bootstrap/pt-BR.lproj/Localizable.strings
Labels: enhancement, translation

#170 Update Localizable.strings (Fr)
  Bootstrap/fr.lproj/Localizable.strings
Labels: enhancement, translation

#153 Add indonesian and Javanese-ID language
  Bootstrap/jv-ID.lproj/Localizable.strings
Labels: enhancement, translation

#138 Localization(zh-TW)
  Bootstrap/zh-TW.lproj/Localizable.strings
Labels: enhancement, translation

#146 Indonesian localization
  Bootstrap/id.lproj/Localizable.strings
Labels: enhancement, translation

#187 optimize some translations(zh-CN)
  Bootstrap/zh-CN.lproj/Localizable.strings
Labels: enhancement, translation

#185 Fix bad word and incorrect on Indonesian (id.lproj)
  Bootstrap/id.lproj/Localizable.strings
Labels: enhancement, translation

#182 Fix Localizable.strings (ja)
  Bootstrap/ja.lproj/Localizable.strings
Labels: enhancement, translation

#181 changed to uk.lproj & fixed strings
  Bootstrap/uk.lproj/Localizable.strings
Labels: enhancement, translation

#186 Update Localizable.strings(zh-CN)
  Bootstrap/zh-CN.lproj/Localizable.strings
Labels: enhancement, translation

#195 fix uk.lproj string error
  Bootstrap/uk.lproj/Localizable.strings
Labels: enhancement, translation

#193 fix Ukrainian lproj (build error otherwise)
  Bootstrap/uk.lproj/Localizable.strings
Labels: enhancement, translation

#216 Create issue form
  .github/ISSUE_TEMPLATE/bootstrap-bug.yml
Labels: enhancement

#233 Update ar Localizable.strings
  Bootstrap/ar.lproj/Localizable.strings
Labels: enhancement, translation

#232 Keep issue template consistency
  .github/ISSUE_TEMPLATE/bootstrap-bug.yml
Labels: enhancement

#230 add language translations[text log][en][th]
  Bootstrap/ViewController.m
  Bootstrap/en.lproj/Localizable.strings
  Bootstrap/th.lproj/Localizable.strings
Labels: enhancement, translation

#227 English improvement
  Bootstrap/en.lproj/Localizable.strings
Labels: translation

#229 更新繁體中文
  Bootstrap/zh-TW.lproj/Localizable.strings
Labels: enhancement, translation
